 
//AUTHENTICATION ACTIONS

export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const AUTHENTICATE_WITHTOKEN = 'AUTHENTICATE_WITHTOKEN';
export const LOGOUT = 'LOGOUT';